### ISSUE TITLE
Vue.js Integration for SPA

### ISSUE THREAD

**Issue by nerddelphi** [elastic/apm-agent-rum-js#447] opened 2019-10-03 12:53 UTC
Hi.

Is there any release date for this agent supporting vue.js for SPA? I need that feature, 'cause I have to manually create transactions for AJAX calls and Single-Page-Application (SPA) calls that do not trigger a page load, and if it will automatically create a transaction for these requests in case there is not an active one currently.

Thanks.

**Comment by axw** [comment] 2019-10-07 02:52
Responded to the Discuss post - closing this as a duplicate of https://github.com/elastic/apm-agent-rum-js/issues/314.

**Closed by axw** 2019-10-07 02:52 UTC
