### ISSUE TITLE
patchEventTarget doubles events (under special conditions)

### ISSUE THREAD

**Issue by christianhaller3000** [elastic/apm-agent-rum-js#1174] opened 2022-02-28 16:55 UTC
When we deploy `apm-agent-rum-js` to our (pretty large) e-commerce website, we are losing some click events.

overwriting the native prototype `window.EventTarget.prototype` or wrapping the native events seems to have side effects
https://github.com/elastic/apm-agent-rum-js/blob/f58bc1b836f1e3caf07b668cbed6df619bdfdc92/packages/rum-core/src/common/patching/event-target-patch.js

Could you offer an config property to bypass the  event listener wrapper?

**Comment by devcorpio** [comment] 2022-03-01 09:35
hI @christianhaller3000 ,

Thanks for bringing this to our notice!

It is possible to disable the event target wrapping making use of [disableInstrumentations](https://www.elastic.co/guide/en/apm/agent/rum-js/4.x/configuration.html#disable-instrumentations) config. In this case the instrumentation to disable would be ```eventtarget```

Let me know if that helps you!

--

Apart from that, I would like to understand better the situation and I would like to ask a couple questions:

- What do you mean with exactly```we are losing some click events```? Is there any interaction failing?
- Could we reproduce somehow that scenario from our side? Is the website accessible?
- If so, could you tell us how to reproduce the issue with the clicks?


Thanks,
Alberto

**Comment by christianhaller3000** [comment] 2022-03-01 14:17
Hi @devcorpio,
disabling the instrumentation does not help.

But I can provide a simple example:

```html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <!-- this is before we add the click event listeners, move this this between -->
    <script src="https://cdn.jsdelivr.net/npm/@elastic/apm-rum@5.10.2/dist/bundles/elastic-apm-rum.umd.js"></script>
    <button>click me and and watch the console.log output</button>
    <script>
        const fn = function () {
            console.log("should be only one time logged");
        };
        document.querySelector('button').addEventListener('click', fn);
    </script>
    <!-- place elastic-apm-rum here and fn will be called twice 😳 -->
    <script>
        document.querySelectorAll('button')[0].addEventListener('click', fn);
    </script>
</body>
</html>
```

- If click the button, you will see console.log **1** time.
- If you move the `elastic-apm-rum.umd.js` *between* the addEventListener statements and click the button, you will see console.log **2** times. ❌
- If you drop `elastic-apm-rum.umd.js` and click the button, you will see console.log **1** time. ✅

So I musst correct myself: we are not losing clicks, we double them by adding the lib.

**Comment by devcorpio** [comment] 2022-03-01 14:58
Hi @christianhaller3000 ,

Thanks for updating the details. Since it's happening even without the agent initialised, there is no configuration flag to prevent this from happening. We will need to have a look and fix it

cc @vigneshshanmugam

**Comment by devcorpio** [comment] 2022-03-10 16:57
Hi @christianhaller3000,

I have been investigating the issue, and there is an explanation behind this behaviour. In your snippet if you replace `console.log ` with `console.trace`

```
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <!-- this is before we add the click event listeners, move this this between -->
    <button>click me and and watch the console.log output</button>
    <script>
        const fn = function () {
            console.trace("should be only one time logged");
        };
        document.querySelector('button').addEventListener('click', fn);
    </script>
    <!-- place elastic-apm-rum here and fn will be called twice 😳 -->
    <script src="https://cdn.jsdelivr.net/npm/@elastic/apm-rum@5.10.2/dist/bundles/elastic-apm-rum.umd.js"></script>
    <script>
        document.querySelectorAll('button')[0].addEventListener('click', fn);
    </script>
</body>
</html>
``` 

you will see something like the screenshot below:

<img width="908" alt="Screenshot 2022-03-10 at 16 31 25" src="https://user-images.githubusercontent.com/15065076/157695799-8c49c5a6-0ae2-430c-9685-f26f64793aa0.png">

The overwriting of window.EventTarget.prototype intent to collect all the `addEventListener` (only for clicks) defined in a website and execute the logic needed to generate `user-interaction` transactions once they are triggered, that means:

1. agent logic
2. execute the original callback defined

With that in mind we should take into account the following scenarios:

1. Adding `apm-agent-rum-js` as the first script of the page will allow the agent to instrument **all** the addEventListeners defined across the page and all the ones that might be created afterwards.  

  ->  that causes only **one** execution (handled by the **agent**)

2. Adding `apm-agent-rum-js` as the last script will not allow the agent to instrument the addEventListeners defined across the page since they have been defined before the agent logic was available. 

  -> that causes only **one** execution.

Note: addEventListeners created during the page's lifecycle will be instrumented properly

3. **the special condition defined in this issue**, steps:
    - execute addEventListener
    - add ```apm-agent-rum-js```
    - execute addEventListener
    
In this scenario, the agent doesn't know anything about the first `addEventListener`, so the browser registers it with the original window.EventTarget.prototype API. On the other hand, the second `addEventListener` will be registered by the agent through the overwritten window.EventTarget.prototype implementation. Causing then the double execution, in the image below we can see it the two listeners defined:

<img width="1364" alt="Screenshot 2022-03-10 at 17 21 54" src="https://user-images.githubusercontent.com/15065076/157707798-83009adf-10cc-455e-ae6f-3aef6593fe4a.png">

# Why is that happening?

The original implementation of window.EventTarget.prototype API (handled by the browsers internally) doesn't duplicate a listener if the callback for the same target was already defined.

```
const callback = () => console.log('hello');
window.addEventListener('click', callback);
window.addEventListener('click', callback);

// The listener will be registered once, since they have the same callback.
```

In the special condition defined in this issue we are seeing one drawback ofthe overwriting of window.EventTarget.prototype API. Via Javascript it's not possible to know if a element has a listener attached and check if the callback was already registered for that target(as they original implementation does), that's the reason behind all of this.

# Recommended workarounds for your scenario

Option A: be sure the agent is the first script of your website.
Option B: initialise the agent [asynchronously](https://www.elastic.co/guide/en/apm/agent/rum-js/current/install-the-agent.html#_asynchronous_non_blocking_pattern). (drawback of this: addEventListeners defined before the execution of the agent will not be instrumented, only the ones added later on in the page's lifecycle)

In this [link](https://www.elastic.co/guide/en/apm/agent/rum-js/current/install-the-agent.html#_synchronous_blocking_pattern) there is more info describing different ways to add the agent in your page.

Let me know if this helps you

Thanks,
Alberto

**Comment by christianhaller3000** [comment] 2022-03-14 11:45
Hi @devcorpio 
thanks for the deep dive!

Option A: For performance reasons, we can not place the agent's javascript blocking and before all other scrips.
Option B: when the agent is loaded asynchronous, our use case is still failing, because we add click events dynamically. 

Sadly, the `disableInstrumentations` option can't prevent this struggle. :-(
For us, this is a show stopper.

**Comment by devcorpio** [comment] 2022-03-29 16:11
I'm going to expose a few proposals **focused on solving this issue**, but before that I would like to show a bit of context, so we are all in the same page

# Context:

Currently, we are patching `Event.target.addEventListener` and `Event.target.removeEventListener` functions once the agent is **loaded** in the browser.
This is something that takes places even with the agent has not been yet initialised. That's why the **disableInstrumentation** config does not apply here. (It's a configuration used when initialising)

To patch before initialising improve our chances of things such as:
- Our listeners always fires before everyone else's.
- Manage also events that have been explicitly called with **e.stopPropagation** or **e.preventDefault**.
- Give our users the possibility of initialising the agent based on a certain flow and despite so make sure all clicks events defined up until that point are already instrumented.

Note: that strategy was thought having mind that the most of our users load the agent as the first script of their page. But our users for performance reasons might decide not to inject the agent as the first script or they can use the [asynchronous / non-blocking pattern](https://www.elastic.co/guide/en/apm/agent/rum-js/current/install-the-agent.html#_asynchronous_non_blocking_pattern)


# Proposals

## Proposal 1: Leveraging the config defined in the script itself

Currently, the agent still allows to define configuration options in the script tag itself. For instance:

` <script src="elastic-apm-rum.umd.min.js" data-api-version="3" data-log-level="debug" crossorigin>`

Since that config is available from the beginning we could leverage this to prevent the instrumentation of **EventTarget** from happening. 


Although, there are multiple trade-offs to have into account:

- That way of defining configuration is not properly documented (there is an [issue](https://github.com/elastic/apm-agent-rum-js/issues/840) related with this btw)
- The current implementation does not work with **data-attributes** containing an array (disableInstrumentation config expects an array)
- This can only work with the [sync](https://www.elastic.co/guide/en/apm/agent/rum-js/current/install-the-agent.html#_synchronous_blocking_pattern) and [async pattern](https://www.elastic.co/guide/en/apm/agent/rum-js/current/install-the-agent.html#_asynchronous_non_blocking_pattern) **but not with bundlers** (unless not in an obvious way, it's true that it would still possible to define the config in the script containing everything but it feels a bit weird)


## Proposal 2: Using a predefined variable to declare configuration

This proposal works as a possible alternative to the first one. Rather than defining the configuration in the script tag we could allow our users through a variable (a particular one) defined in their website. For instance:

```
   window.elasticApmConfig = {
         apiVersion: 3,
         disableInstrumentations: ['page-load', 'event-target', // etc...],
         // etc
   }
```
And then check the existence of that configuration when **loading** and **initialising** the agent. We could even leverage that new way of doing to permit our users to initialise the agent without parameters since they might be defined all required parameters already. If a config is also set when initialising both configs would be merged. 

**Important**: this variable should be defined before the agent is loaded if want to leverage it for things such as avoiding instrumentations.

The main benefits compared with the first proposal are:

- It work with bundles too.
- Doesn't need to serialise the **data-attribute** containing arrays to proper javascript structures before checking the config. It would be the very same object structure used in the initialisation.

The main drawback is that it would be an extra way of adding configuration, with this new it would be 3 different ways. More code to maintain.


## Proposal 3: Patch eventTarget when initialising

If we do this, we could leverage the current configuration to decide if the instrumentation should be disabled or not

**Drawbacks**

- We would be putting in risk all the benefits described in the **context** section.
- Some of our users might have a different behaviour when it comes to **user-interactions**, I'm thinking of the ones that might load the agent based on a certain flow rather than the ones that initialise the agent next to where the script was injected.


## Recommended proposal:

If we take into consideration current priorities and the future steps we have in mind I would choose **Proposal 1** but I would like to know your opinion first @vigneshshanmugam when you have time. Nonetheless, despite the proposal (maybe it's a different one not described here!) we end up choosing it will be nice to weigh trade-offs of this kind in future developments 😄

**Closed** 2022-05-12 17:10 UTC
Labels: bug

**Comment by christianhaller3000** [comment] 2022-05-16 12:48
Thank you :-)
