### ISSUE TITLE
Built with warning: "export 'Promise' was not found in 'es6-promise'"

### ISSUE THREAD

**Issue by adolt** [elastic/apm-agent-rum-js#375] opened 2019-08-13 07:25 UTC
Hi, we've been using Elastic APM for couple of months.

Recently, we want to move version 3.0 to the latest v4.4.2. I saw there are some breaking changes, including **resolve main field to source file**. So I added it to babel-loader
<img width="351" alt="image" src="https://user-images.githubusercontent.com/25565814/62922147-4f74fd80-bddd-11e9-9c51-65a3e803af96.png">

But while building the project, I got some warnings
<img width="718" alt="image" src="https://user-images.githubusercontent.com/25565814/62922223-77fcf780-bddd-11e9-9b8f-20aec7cd7135.png">

Is there some potential effects? Or how can I avoid this?

**Comment by vigneshshanmugam** [comment] 2019-08-13 10:22
@adolt We added support for ES6 Modules https://github.com/elastic/apm-agent-rum-js/pull/237, But that is not a breaking change since the code we publish the transpiled code in `main` field and the Modules aware bundlers like webpack, rollup etc would use the `module` field to do better tree shaking and dead code elimination of the imported modules. 

Also, you do not need to run `babel-loader` on the `@elastic/*` modules. Can you paste the full bundling config?

**Comment by adolt** [comment] 2019-08-13 10:46
I've remove some parts, like `url-loader` etc.

```javascript
{
  entry: {
    app: paths.js,
  },
  output: {
    path: paths.dist,
    filename: 'static/js/[name].[chunkhash:8].js',
    chunkFilename: 'static/js/[name].[chunkhash:8].chunk.js',
    publicPath,
  },
  resolve: {
    modules: [paths.src, 'node_modules'],
    extensions: ['.js', '.vue'],
    symlinks: false,
  },
  module: {
    rules: [
      {
        test: /\.vue$/,
        enforce: 'pre',
        loader: 'eslint-loader',
        include: paths.js,
      },
      {
        test: /\.js$/,
        enforce: 'pre',
        loader: 'eslint-loader',
        include: paths.js,
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader',
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: paths.js,
      },
    ],
  },
}
```

**Comment by vigneshshanmugam** [comment] 2019-08-13 15:33
Just tested it out with `webpacK@3.11.0` and `@elastic/apm-rum@4.4.2` and I am not able to reproduce the issue. 

*app.js*
```js
const apm = require("@elastic/apm-rum");

function invoke() {
  apm.init({
    serviceName: "test"
  });
}

invoke();

```

*webpack.config.js*
```js
const path = require("path");

module.exports = {
  entry: path.join(__dirname, "app.js"),
  output: {
    filename: "app.bundle.js"
  },
  resolve: {
    modules: [path.join(__dirname), "node_modules"],
    extensions: [".js", ".vue"],
    symlinks: false
  }
};
```

If you can create a dummy repo to reproduce the problem, that would be great.

**Comment by adolt** [comment] 2019-08-13 15:47
I’m using ‘import’ instead of ‘require’. Is it the problem?

**Comment by vigneshshanmugam** [comment] 2019-08-13 19:32
No, it should not matter. I did try with import statements as well and it works the same. Can you try cleaning your node_modules and try again? If it does not help, Please share a sample repo and I can help you fix the problem.

**Comment by adolt** [comment] 2019-08-14 05:14
Hi, I've created a [repo](https://github.com/adolt/apm-issue-example), and found that `babel-plugin-transform-runtime` cause the issue. But don't why.

**Comment by vigneshshanmugam** [comment] 2019-08-14 08:58
Thanks for providing the repo. As I stated above in my above comment https://github.com/elastic/apm-agent-rum-js/issues/375#issuecomment-520778702, We publish the transpiled version of the core in  `main` field and original source (untranspiled) in the `module` field.  Since webpack understands resolving from both `main` and `module`, you can decide how to apply the babel transformation to the code depending on your targets by using  babel-loader and applying the preset https://babeljs.io/docs/en/babel-preset-env. In your code you did not pass the required presets/config handling the import statements. 

```js
 {
  test: /\.js$/,
  loader: 'babel-loader',
  include: [/@elastic/, paths.js],
  options: {
    presets: ['env'],
  },
}
```

There is also one other solution where you can inform webpack to resolve only to `main` field and not `module`. 

```js
resolve: {
    // mainFields: ['main'],
},
```

Hope it helps, let me know if you need any help.

**Comment by adolt** [comment] 2019-08-14 10:11
Thanks for reply!
I've try to add `options` field to `babel-loader`, but warnings still remain. And I think it should not be an issue of this repo. I'll close it.

Anyway, very appreciate to your patience, thanks!

**Closed** 2019-08-14 10:22 UTC

**Comment by vigneshshanmugam** [comment] 2019-08-14 10:31
`options` should work or you can also use `.babelrc` file with the same set of config and it should get picked up. Not sure why you are seeing issues, I tested with your example repo. I can give a PR if you are still running in to issues. Thanks.
