### ISSUE TITLE
Does not work with Angular 10

### ISSUE THREAD

**Issue by emzet** [elastic/apm-agent-rum-js#922] opened 2020-10-16 14:17 UTC
Trying to implement with latest Angular version 10.1.4 by provided guide https://www.elastic.co/guide/en/apm/agent/rum-js/current/angular-integration.html throws error:

```
Uncaught TypeError: Reflect.metadata is not a function
    at Module.6SBv (apm-service.js:8)
    at __webpack_require__ (bootstrap:84)
    at Module.+/6d (index.js:1)
    at __webpack_require__ (bootstrap:84)
    at Module.ZAI4 (app.module.ts:1)
    at __webpack_require__ (bootstrap:84)
    at Module.<anonymous> (main.ts:1)
    at Module.zUnb (main.ts:31)
    at __webpack_require__ (bootstrap:84)
```

When add polyfill https://stackoverflow.com/questions/53790880/uncaught-typeerror-reflect-definemetadata-is-not-a-function-on-angular-7-produc it throws another error:

```
Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.
    at getCompilerFacade (core.js:562)
    at Function.get (core.js:10800)
    at getInjectableDef (core.js:333)
    at R3Injector.get (core.js:11098)
    at injectInjectorOnly (core.js:899)
    at Module.ɵɵinject (core.js:903)
    at Object.AppModule_Factory [as factory] (app.module.ts:111)
    at R3Injector.hydrate (core.js:11289)
    at R3Injector.get (core.js:11111)
    at core.js:11148
```

Also tried with clean Angular application and adding polyfill directly into index.html,

`<script src="https://cdnjs.cloudflare.com/ajax/libs/reflect-metadata/0.1.13/Reflect.min.js" integrity="sha512-jvbPH2TH5BSZumEfOJZn9IV+5bSwwN+qG4dvthYe3KCGC3/9HmxZ4phADbt9Pfcp+XSyyfc2vGZ/RMsSUZ9tbQ==" crossorigin="anonymous"></script>`

but does not work too, throws same error as above (the second one).

Maybe some hint here: https://angular.io/guide/deprecations#reflect-metadata

**Comment by ValdisThomann** [comment] 2020-10-30 04:47
@emzet I was able to resolve the second error by adding `import '@angular/compiler'` to the `main.ts` file.

That being said, it's a hack and isn't recommended for production. I'm only using it to evaluate Elastic APM.

**Comment by deefactorial** [comment] 2020-11-26 19:47
The `Reflect` issue can be resolved by adding:

```js
import 'core-js/features/reflect';
```

to your `pollyfills.ts` file 
As for the JIT issue, it isn't resolved for production builds with AOT. Angular 10 uses AOT for dev builds and production builds with IVY so this fix https://github.com/elastic/apm-agent-rum-js/pull/734 doesn't appear to be working for Angular 9 and Angular 10 builds.

**Comment by deefactorial** [comment] 2020-11-26 21:34
looks like the package `@elastic/apm-rum-angular` is missing the `.metadata.json` file so when `ngcc` scans the packages it doesn't find the package.
https://indepth.dev/angular-compatability-compiler

**Comment by vigneshshanmugam** [comment] 2020-11-29 14:22
I agree that our Angular integration is not great at the moment when supporting the AOT build pipeline, We plan to address this issue pretty soon with #757 at-least in the upcoming releases. If anyone is interested in working on this, Please let us know and i am happy to help before we do a proper implementation.

**Comment by emzet** [comment] 2021-01-04 02:13
@vigneshshanmugam any progress ?

**Comment by vigneshshanmugam** [comment] 2021-03-25 14:23
We published the RUM Angular integration v2 Alpha which includes support for Angular 9. Would you be able to test it and let us know if it fixes your problem. 

```
npm install @elastic/apm-rum-angular@alpha
```

You have to make small changes to the initialization code. Docs here - https://github.com/elastic/apm-agent-rum-js/blob/cc4aba03d7f843e40f7256ee5a73fb74d4c18c9a/docs/angular-integration.asciidoc

Once these issues are addressed, will go ahead do the proper release. Thanks for the help in advance!

**Comment by vigneshshanmugam** [comment] 2021-04-19 22:57
Version 2.x.x has been published with support for angular 9-11. Let us know if you face any issues.

**Closed by vigneshshanmugam** 2021-04-19 22:57 UTC

**Comment by mukuldani** [comment] 2023-09-21 07:33
@vigneshshanmugam I m using angular 10 and installed @elastic/apm-rum-angular - 2.1.7 in my App but according to the Doc the AppModule is to be imported and service is to be defined but getting an Error as below 
`apm.module.d.ts(25, 100): This likely means that the library (@elastic/apm-rum-angular) which declares ApmModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.`

**Comment by devcorpio** [comment] 2023-09-21 13:10
Hi @mukuldani,

Thanks for reaching out!

We have tested `@elastic/apm-rum-angular - 2.1.7` with angular 10 and we cannot reproduce your case.


<img width="448" alt="Screenshot 1" src="https://github.com/elastic/apm-agent-rum-js/assets/15065076/067c359e-ff7f-4ec1-ae2f-3d04233cfe4d">

<img width="815" alt="Screenshot 2" src="https://github.com/elastic/apm-agent-rum-js/assets/15065076/2fabed3b-824f-407c-8373-b2ffdfb39268">


I would like to ask you if you can make sure that in fact you are using the versions you are mentioning:

- @elastic/apm-rum-angular - 2.1.7
- angular 10.

You can check that in the `package-lock` of your project or in the `package.json` of each of those packages that you will find in node_modules.

Saying this because, the log you are showing [started to appear ](https://github.com/elastic/apm-agent-rum-js/issues/1345#issuecomment-1546042707)in the angular 16 version (when it comes to our agent), not before. That was the reason for the [3.0.0 release.](https://www.elastic.co/guide/en/apm/agent/rum-js/current/release-notes-5.x.html#_features_2), docs [here](https://www.elastic.co/guide/en/apm/agent/rum-js/current/angular-integration.html).

--

Additionally, I understand that you might be facing a "corner" case because of a particular configuration. Please have a look at this link when you have time. https://stackoverflow.com/questions/63627932/angular-10-libraries-and-ivy-ngcc-compatibility

Thanks,
Alberto

**Comment by mukuldani** [comment] 2023-09-22 05:42
@devcorpio thank u for the guidance. I re-checked my angular version its the same as u mentioned in your comment also the  @elastic/apm-rum-angular version is 2.1.7 but this might be the edge case which i m facing. I upgraded the version and it was working fine for now. 

Thanks 
Mukul
