### ISSUE TITLE
Provide TypeScript typings for APIs

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#217] opened 2019-03-18 12:36 UTC
There are multiple benefits of providing typings for the users. First generally IDEs have support for typing files and can provide auto-completion even in JS code. It also helps users identify and fix issues related to the API changes.

**Comment by unicrus** [comment] 2019-04-05 08:50
It's a duplicate of #70.

**Comment by vigneshshanmugam** [comment] 2019-04-05 09:31
Thanks @unicrus , Closing this issue.

**Closed by vigneshshanmugam** 2019-04-05 09:31 UTC
Labels: [zube]: Backlog
