### ISSUE TITLE
"page-load" transaction._end value is not proper

### ISSUE THREAD

**Issue by adolt** [elastic/apm-agent-rum-js#474] opened 2019-11-07 09:20 UTC
Hi, we've been using for couple of months. And recently, we found that there are some cases where `transaction.duranton` is abnormally long. After read through the code, I found that `transaction._end` will get the latest `span._end` value, which I think is not very proper:
1. if user fire a xhr that takes very long time before `load event`, transaction will not be sent before the xhr ends although `load` event is fired immediately.
2. normally we'll gather information from kibana -> APM, where `Avg.duration` and `95th  percentile` value is calculated using `transaction.duration` value, which is not corresponding to the real `load event` time.
3. the function name here is called `getLatestNonXHRSpan`, but is it implemented properly? If YES, it's understandable because xhr will not influence the `load event` time where resource fetching will.
https://github.com/elastic/apm-agent-rum-js/blob/228e157851f4df7448f8bfcdd4b4b57129707992/packages/rum-core/src/common/utils.js#L360

And if I misunderstood something, sorry about that.🤭

**Comment by vigneshshanmugam** [comment] 2019-11-08 21:16
Transaction end will reflect the latest non xhr spans and `load event` never fires before all resources are fetched. In which case, the latest non xhr spans end would always be less than the transaction end. 

I am not able to think of a scenario where this might cause issues. Could you please provide an example?

**Comment by adolt** [comment] 2019-11-10 03:19
Yeah, but I didn’t see any code in `getLatestNonXHRSpan` function body to exclude the xhr spans.

**Comment by vigneshshanmugam** [comment] 2019-11-11 09:29
This is the part that deals with XHR spans which are marked as external https://github.com/elastic/apm-agent-rum-js/blob/228e157851f4df7448f8bfcdd4b4b57129707992/packages/rum-core/src/common/utils.js#L364-L368

**Comment by adolt** [comment] 2019-11-20 12:49
`transaction.duration` should be the time cost before `onLoad` event is fired, and I've mentioned some reasons above. But currently it depends on the XHR.

I've created a [repo](https://github.com/adolt/apm-transaction-issue-example) to show that the XHR span will influence the `end` time of the page-load transaction.

**Comment by vigneshshanmugam** [comment] 2019-11-20 14:27
Thanks a lot for providing a repo. I can reproduce the issue and can confirm its a bug. Will update here with more details.

**Comment by adolt** [comment] 2019-11-21 04:02
Very appreciate!

**Comment by vigneshshanmugam** [comment] 2019-12-02 15:31
After discussing with some colleagues and thought process, we want to capture the overall user experience when the page is loaded and capture whatever that is posssible and use it as part of the page-load transaction.  The naming might confuse the users, the page load transaction duration does not reflect the window load event since the duration of the transaction can extend beyond the window load since we would want to instrument all possible actions performed by the user. 

If you want to accurately measure the window load event, we already capture the information and send it as part of transaction agent marks. https://github.com/elastic/apm-agent-rum-js/blob/777078a564eee6cc2f13c933fa552b01c1114e99/packages/rum-core/src/common/utils.js#L385-L400


We also create a span(`'Fire "load" event'`) to capture the duration of the onload end and start event which might be useful for your use case as well - https://github.com/elastic/apm-agent-rum-js/blob/777078a564eee6cc2f13c933fa552b01c1114e99/packages/rum-core/src/performance-monitoring/capture-navigation.js#L60

**Comment by jahtalab** [comment] 2019-12-18 12:51
We should add a note in our docs to make the difference between `page-load` transactions and load event clear. Also pointing out that the exact load event timings are captured via the marks and the `Fire "load" event` span.

**Closed** 2019-12-23 10:13 UTC
Labels: docs
