### ISSUE TITLE
sourcemap to error stack doesn't work

### ISSUE THREAD

**Issue by LHB6540** [elastic/apm-agent-rum-js#1289] opened 2022-10-09 06:59 UTC
follow this page [How to apply source maps to error stack traces when using minified bundles](https://www.elastic.co/guide/en/apm/guide/8.4/sourcemaps.html)
I am throwing an exception in vite+vue3 project(src/App.vue)
```
try {
      throw 'Parameter is not a number!'
}
catch(err) {
      // error is not defined
      console.log(error)
} 
```
and add the following configuration in the file vite.config.ts and run npm run bulid to generate the sourcemap
```
export default defineConfig({
  plugins: [vue()],
  build: {
    sourcemap: true                                                                                                                                                                         
  },
```
In the end I got the sourcemap in the project folder，and configure nginx to point to this directory
```
dist
├── assets
│   ├── index.c447a54c.js
│   └── index.c447a54c.js.map
├── favicon.ico
└── index.html
```
Under this directory path, I execute curl and successfully upload the sourcemap to kibana
```
cd dist
curl -X POST "https://${kibana}/api/apm/sourcemaps" \
  -H 'Content-Type: multipart/form-data' \
  -H 'kbn-xsrf: true' \
  -H 'Authorization: ApiKey ${key}' \
  -F 'service_name="demo"' \
  -F 'service_version="1.0"' \
  -F 'bundle_filepath="assets/index.c447a54c.js"'  \
  -F 'sourcemap=@assets/index.c447a54c.js.map'
```
Response:
```
{
  "type":"sourcemap",
  "identifier":"\"demo\"-\"1.0\"",
  ...
}
```
But in kibana, the stack is not mapped to the code, as shown below
![image](https://user-images.githubusercontent.com/41095303/194742395-7ac8c62b-8aac-4c27-9c04-afa559198b4c.png)

**Comment by devcorpio** [comment] 2022-10-10 14:53
Hi @LHB6540,

Thanks for reaching out!

Are you using the [legacy standalone](https://www.elastic.co/guide/en/apm/guide/8.4/overview.html) APM server? or are you using the [APM integration](https://www.elastic.co/guide/en/apm/guide/8.4/upgrade-to-apm-integration.html)?

The value of your **bundle_filepath** configuration is a relative URL (**assets/index.c447a54c.js**). That's important because relative path for sourcemaps have not been working with APM Integration in recent versions due to a bug. The fix will be delivered on 8.5.

More details here: https://github.com/elastic/apm-server/issues/8650

--
This [discuss forum thread](https://discuss.elastic.co/t/uploading-sourcemaps-from-aix-webserver/303526/15?u=alberto_delgado) might provide you with further guidance. It's a step by step guide. Except for the endpoint exposed there (for version 7.x) everything else applies for 8.x.



Cheers,
Alberto

**Comment by LHB6540** [comment] 2022-10-12 03:14
> 
My ES Stack version is 8.3.3.
As you mentioned, I replaced bundle_filepath with absolute path "http://192.168.27.148/assets/index.cf47a304.js",
But sourcemap still doesn't work.
```
cd dist
curl -X POST "https://${kibana}/api/apm/sourcemaps" \
  -H 'Content-Type: multipart/form-data' \
  -H 'kbn-xsrf: true' \
  -H 'Authorization: ApiKey ${key}' \
  -F 'service_name="demo"' \
  -F 'service_version="1.0"' \
  -F 'bundle_filepath="http://192.168.27.148/assets/index.c447a54c.js"'  \
  -F 'sourcemap=@assets/index.c447a54c.js.map'
```

By the way, like the example given in [discuss forum thread](https://discuss.elastic.co/t/uploading-sourcemaps-from-aix-webserver/303526/15?u=alberto_delgado) you just mentioned, add a complete web demo to the document, including the project structure, js errors in the example, sourcemap generation, uploading to kibana and other steps, perhaps for users to understand sourcemap Workflow and usage are more helpful

**Comment by LHB6540** [comment] 2022-10-12 04:06
After changing some details of curl's parameters, sourcemap works fine
-F 'service_name="demo"' ->  -F service_name="demo"
-F service_version="1.0" -> -F service_version="1.0"
-F 'bundle_filepath="http://192.168.27.148/assets/index.c447a54c.js"' -> -F bundle_filepath="http://192.168.27.148/assets/index.c447a54c.js"
-F 'sourcemap=@assets/index.c447a54c.js.map' -> -F sourcemap="@assets/index.c447a54c.js.map"

But the original writing method is the official document writing method, maybe the document needs to be improved

By the way，the problem of bundle_filepath is really exist in version 8.3.3
only when bundle_filepath="http://192.168.27.148/assets/index.c447a54c.js，this can work

**Comment by andriijas** [comment] 2022-10-13 11:32
Cant get it to work with 8.x, it worked in 7.x

Have same issue as @LHB6540 

The sourcemap is confirmed in kibana (/api/apm/sourcemaps)  - its uploaded

however I can see this error in discover

```
Unable to find sourcemap.url for service.name=test service.version=3.29.0.398991 bundle.path=https://.../main.e7cabb53a48bec967b94.js
```

yes the bundle.path link works if i click it, and the service name and version is correct, the error/exception is listed in apm service

![Screenshot 2022-10-13 at 13 31 31](https://user-images.githubusercontent.com/33141/195585432-e8985893-413c-41af-9c4a-ea0856810439.png)

**Comment by devcorpio** [comment] 2022-10-13 14:57
Hi @LHB6540,

Glad to know that it's working 😄 

Btw, thank you for creating the [PR](https://github.com/elastic/apm-server/pull/9359) in the APM Server repo 👍 

> By the way, like the example given in [discuss forum thread](https://discuss.elastic.co/t/uploading-sourcemaps-from-aix-webserver/303526/15?u=alberto_delgado) you just mentioned, add a complete web demo to the document, including the project structure, js errors in the example, sourcemap generation, uploading to kibana and other steps, perhaps for users to understand sourcemap Workflow and usage are more helpful

I agree with you that we need to update our documentation based on that, Thanks for pointing it out!

> By the way, the issue with bundle_filepath does exist in version 8.3.3
> only when bundle_filepath="[http://192.168.27.148/assets/index.c447a54c.js，sourcemap](http://192.168.27.148/assets/index.c447a54c.js%EF%BC%8Csourcemap) can work

Yes, in version 8.3.3 is still failing, the fix will be released in version 8.5. 


Cheers,
Alberto

**Comment by andriijas** [comment] 2022-10-13 15:00
@devcorpio is there any eta on 8.5 or its ready when it's ready?

**Comment by andriijas** [comment] 2022-10-13 15:48
I skimmed through the code in this MR https://github.com/elastic/apm-server/pull/9082
This is from our own kibana:
```
    "exception": [
        {
          "stacktrace": [
            {
              "exclude_from_grouping": false,
              "abs_path": "https://acme.inc/main.3af0a0836523dbf1e977.js",  <-- should this be the JS file or the MAP file
              "filename": "main.3af0a0836523dbf1e977.js",
              "sourcemap": {
                "error": "unable to find sourcemap.url for service.name=client-featuretest1 service.version=3.29.0.399158 bundle.path=https://acme.inc/main.3af0a0836523dbf1e977.js" <-- should this be the JS file or the map file?
              },
              "line": {
                "number": 1,
                "column": 362350
              },
              "function": "<anonymous>"
            }
          ],
          "message": "Uncaught TypeError: Co.crashNburn8 is not a function",
          "type": "TypeError"
        }
```

Are there any other known issues with fleet and kibana matching the uploaded sourcemap than the linked MR which only seem to make it possible to use relative urls again which also worked in kibana 7

**Comment by devcorpio** [comment] 2022-10-13 17:03
Hi @andriijas,

> @devcorpio is there any eta on 8.5 or its ready when it's ready?

It is expected to be released around Oct/Nov

> Are there any other known issues with fleet and kibana matching the uploaded sourcemap than the linked MR which only seem to make it possible to use relative urls again which also worked in kibana 7

The only known issue is related to relative paths. With absolute paths you shouldn't been facing any issue. 

Have you tried following [this]([discuss forum thread](https://discuss.elastic.co/t/uploading-sourcemaps-from-aix-webserver/303526/15?u=alberto_delgado)) guide?

--

@elastic/apm-server could you provide help to @andriijas with [this](https://github.com/elastic/apm-agent-rum-js/issues/1289#issuecomment-1277826512)?


Thanks,
Alberto

**Comment by andriijas** [comment] 2022-10-13 18:07
Thanks for helpng out @devcorpio 

Yeah we've been double checking our curl script so many times.

sourcemaps are verified uploaded in /api/apm/sourcemaps
but somehow the mapping fails anyway

Something thats interesting is that same error (grouped) sometimes get the source map exception, sometimes not. check this:

https://user-images.githubusercontent.com/33141/195673036-325d8d1f-f6dc-4f9f-a2f6-536d090668d9.mov

**Comment by andriijas** [comment] 2022-10-13 18:18
also, is it possible to query /api/apm/sourcemaps  with just the entries, basically all data without the actual sourcemap inline?
to query and understand whats really in the database

also, there is missing some kind of purging command, right now we need to make a script that deletes source map and fleet entry one by one - or?

**Comment by axw** [comment] 2022-10-14 06:30
> Something thats interesting is that same error (grouped) sometimes get the source map exception, sometimes not. check this:

@andriijas can you share the JSON for one of the documents which has the "unable to find sourcemap.url" error, and one which does not?

**Comment by axw** [comment] 2022-10-14 06:36
> also, is it possible to query /api/apm/sourcemaps with just the entries, basically all data without the actual sourcemap inline?
to query and understand whats really in the database

No. Can you use [`jq`](https://stedolan.github.io/jq/) to filter what you're interested in?

> also, there is missing some kind of purging command, right now we need to make a script that deletes source map and fleet entry one by one - or?

There's no API for bulk deletion at present. How would you expect this to work?

**Comment by andriijas** [comment] 2022-10-14 07:58
> > Something thats interesting is that same error (grouped) sometimes get the source map exception, sometimes not. check this:
> 
> @andriijas can you share the JSON for one of the documents which has the "unable to find sourcemap.url" error, and one which does not?

https://gist.github.com/andriijas/21dd841ec3b9b0e5ab8426c553aa4bb7
https://gist.github.com/andriijas/f2acc469fd0bfc7f0eaea0ba68599bf5

**Comment by andriijas** [comment] 2022-10-14 08:54
From what I can tell the exception is thrown here https://github.com/elastic/apm-server/blob/main/internal/sourcemap/fleet.go#L99

Whats not clear to me is how kibana/apm puzzles the url together to match with the bundle path I provide from uploading the sourcemap

**Comment by simitt** [comment] 2022-10-14 11:14
The `abs_path` of a stacktrace frame needs to match the `bundle_filepath` from the uploaded sourcemap. Until the previously mentioned bugfix is released, the `bundle_filepath` needs to be an absolute path.

**Comment by andriijas** [comment] 2022-10-14 11:18
> The `abs_path` of a stacktrace frame needs to match the `bundle_filepath` from the uploaded sourcemap. Until the previously mentioned bugfix is released, the `bundle_filepath` needs to be an absolute path.

But as you see in the first gist link above the abs_path and the bundle_path matches

**Comment by andriijas** [comment] 2022-10-16 11:50
https://github.com/elastic/apm-server/issues/9372

**Comment by axw** [comment] 2022-10-17 01:33
@andriijas thanks for providing the documents. I still don't know why sometimes it works and sometimes it doesn't I'm afraid. As noted on https://github.com/elastic/apm-server/issues/9372, there was a bug in Kibana that was fixed in 8.3.0, so please upgrade and let us know if you still have issues.

Coming back to this:

> When we get it working properly we probably dont need it, unless we need to purge entries older than 3 months for example.

I suppose it would be helpful to have a way to delete source maps that were created before `$SOME_TIME`. Perhaps also a way of deleting source maps that haven't matched anything since `$SOME_TIME`? With the latter, we might be able to provide a "purge source maps if they haven't matched any events for X amount of time" configuration. Would that be helpful?

**Comment by andriijas** [comment] 2022-10-17 06:17
@axw Thanks we will update to 8.3 during the day.

Yes that feature would be really good!

**Comment by axw** [comment] 2022-10-17 06:40
@andriijas I've opened https://github.com/elastic/apm/issues/706 to track the enhancement. Please feel free to leave comments on there.

**Comment by devcorpio** [comment] 2022-10-17 07:36
Thank you to everyone for digging into this!

**Closed by devcorpio** 2022-10-17 07:36 UTC

**Comment by andriijas** [comment] 2022-10-18 06:32
Upgrading to 8.4 resolved our issues, thanks everyone for your time, effort and kindness ❤️

**Comment by axw** [comment] 2022-10-18 06:51
Woohoo! Thanks @andriijas for reporting back.
