### ISSUE TITLE
APM is not sending to server

### ISSUE THREAD

**Issue by eliaskardel** [elastic/apm-agent-rum-js#329] opened 2019-07-16 11:14 UTC
**Two Szenarious:** 
**Sends Data to Server:**
                    const transaction = apm.startTransaction('delete', 'custom');
                    const span = transaction.startSpan('delete', 'custom');
                    const new_error = new Error('bla')
                    EndAPMScopeWithError(apm, new_error , transaction, span)
               
            
**Does not send data to Server**
                    const transaction = apm.startTransaction('delete', 'custom');
                    const span = transaction.startSpan('delete', 'custom');
                    
                    axios.delete(this.url, {
                        data: {
                            objects: validObjList,
                        },
                    })
                        .then(function(response) {
                            EndAPMScope(apm, response, transaction, span)
                            resolve(true);
                        })
                        .catch(function(error) {
                            //debugger;
                            EndAPMScopeWithError(apm, error, transaction, span)
                            reject(error);
                        });

The axios request fails because of a time out. I see the transaction in the debug log. However it never ends up in elastic search. 

Attached a screenshot of the debug log.
![image](https://user-images.githubusercontent.com/25151768/61290037-2ad03a80-a7cb-11e9-8903-0ba1656e9ebc.png)

The message 'Could not create a payload from the Transaction' caught my attention. 

My APM config is: 

    const apm = initApm({
        serviceName: '20190712',
        logLevel: 'debug',
        errorThrottleLimit:100, 
        errorThrottleInterval:3000,
        transactionThrottleLimit:100, 
        etransactionThrottleInterval:300,
        environment: process.env.NODE_ENV,
        });

Any Hints on this? The construction with the request I are successful in other parts of the code. Also in case of request time outs. 

Thanks

**Comment by vigneshshanmugam** [comment] 2019-07-16 13:56
@eliaskardel Thanks for the issue. From the looks, I could not easily figure out what would be the cause of the dropped transaction. As you already stated, we do log with the error message `'Could not create a payload from the Transaction'`

https://github.com/elastic/apm-agent-rum-js/blob/e348874feb128be347814b93b3d654e9c76b92c5/packages/rum-core/src/performance-monitoring/performance-monitoring.js#L62-L69

only when these hold true 

+ transaction is never ended
+ transaction duration is greater than threshold set in config using `transactionDurationThreshold` 
+ transaction does not contain spans
+ browser was not responsive

Code link - https://github.com/elastic/apm-agent-rum-js/blob/e348874feb128be347814b93b3d654e9c76b92c5/packages/rum-core/src/performance-monitoring/performance-monitoring.js#L194-L200

From your transaction data, I don't see any issues other than with the duration, Did you by any chance set the `transactionDurationThreshold` to some other value in the APM config? By default we set it to `60000`. Probably the dropped transaction duration is more than the threshold.

**Comment by eliaskardel** [comment] 2019-07-17 08:43
Good hints! I fixed it by setting checkBrowserResponsiveness to false. Thanks for pointing that out.

**Comment by vigneshshanmugam** [comment] 2019-07-17 08:57
Great to hear. We do log those cases when the browser was not responsive as well https://github.com/elastic/apm-agent-rum-js/blob/e348874feb128be347814b93b3d654e9c76b92c5/packages/rum-core/src/performance-monitoring/performance-monitoring.js#L230-L238

Did you see that in console? I am asking because of what might be the actual trigger that made the browser not responsive.

**Comment by eliaskardel** [comment] 2019-07-17 09:34
Yes. Saw that too. But did not know what to do with it, before you told me.

**Comment by vigneshshanmugam** [comment] 2019-07-17 10:16
Cool, Can you give provide some details on the application itself and show how a screenshot of the transaction in Kibana UI? Asking it because we are planning to change the implementation of that browser responsive check and we can consider a real use case before doing that.

**Comment by jahtalab** [comment] 2019-07-17 10:59
Specifically, in this case it seems that the browser really was not responsive enough. Does your application block the main thread to cause the browser to be unresponsive?

**Comment by eliaskardel** [comment] 2019-07-17 15:01
We are developing a web app for object labeling. The app is based on Google Firebase and VueJS.  
The app is running at high loads because it has to stream picture and videos files. Everything is currently 
happening in the same thread.  

![pic](https://user-images.githubusercontent.com/25151768/61385923-9988c300-a8b3-11e9-8eaa-83ee6c201ab7.png)

**Comment by vigneshshanmugam** [comment] 2019-07-18 10:13
That explains it, Thanks for providing more details. I am closing the issue since we figured out a solution. 

Please do let us know if you run in to any issues.

**Closed by vigneshshanmugam** 2019-07-18 10:13 UTC
