### ISSUE TITLE
An Ivy distribution library version

### ISSUE THREAD

**Issue by daniellrsouza** [elastic/apm-agent-rum-js#1363] opened 2023-04-06 21:13 UTC
Any idea when there will be a new version with compatibility to the Ivy compiler?

![image](https://user-images.githubusercontent.com/21343507/230494511-794f8d3b-b3bc-4b2b-b79a-d82fbd588dcc.png)

**Comment by n4imLess** [comment] 2023-04-13 11:26
I'd consider this a duplicate of #1345. With Angular 16 on the horizon we need an Ivy distribution anyways.

**Comment by devcorpio** [comment] 2023-07-18 18:10
as mentioned [here](https://github.com/elastic/apm-agent-rum-js/issues/1345#issuecomment-1640658765) the new version has been released

**Closed by devcorpio** 2023-07-18 18:10 UTC
