### ISSUE TITLE
Spans missing in fast transactions & Incorrect Transaction Time 

### ISSUE THREAD

**Issue by suchcodemuchwow** [elastic/apm-agent-rum-js#1120] opened 2021-12-16 16:34 UTC
Hi folks, as operations team we have been running bunch of performance tests on kibana and looking transaction details using APM UI. We found out that with same jobs we get different results in timeline view. [Here]() when you look at fast transaction it's clear that spans that has bundle requests just skipped in UI or it doesn't even reported by agent but when you compare with slower transactions, bundle requests are there. I would like to know if it's expected behavior or if there is something wrong with UI or apm agents.

Edit: It also seems like transaction time is not correct considering fast transactions but the reason for that might be separate issue.

cc @tylersmalley @spalger

**Comment by paulb-elastic** [comment] 2021-12-20 15:02
@devcorpio / @vigneshshanmugam any comments/advice we can give here?

**Comment by devcorpio** [comment] 2021-12-20 16:06
Hi @suchcodemuchwow,

I was trying to analyse the information that you are sharing but for some reason I'm not able to access to it.

When it comes to: "_when you look at fast transaction it's clear that spans that has bundle requests just skipped in UI or it doesn't even reported by agent but when you compare with slower transactions, bundle requests are there._"

Currently the RUM agent sends transactions to the APM server in short intervals (500ms by default). There is an [issue](https://github.com/elastic/apm-agent-rum-js/issues/195) that require works in the RUM agent and is related with how often the agent sends APM data.

Because of that I'm venturing to stay that this behaviour is something that can expect (at least until that issue is done)

Any thoughts on this @vigneshshanmugam?

**Comment by vigneshshanmugam** [comment] 2021-12-20 19:13
@suchcodemuchwow I checked the transaction you have listed and can see the span data missing for some of the transactions. 

+ Do we know if the transaction was unsampled? RUM agent drops spans and context info for all unsampled transactions. 

I don't have a strong suggestion other than the unsampled flag, It's highly unlikely that the agent would be missing to report those spans as it does capture other details properly. If you can reproduce this issue, I am happy to discuss with you on zoom.

**Comment by suchcodemuchwow** [comment] 2021-12-27 15:21
@vigneshshanmugam We are using ELASTIC_APM_TRANSACTION_SAMPLE_RATE=1.0 which I believe preventing sampling. Are there any other variables we can use to totally disable sampling ? 

@devcorpio Ahh sorry I guess that cluster only belongs to operations team. I uploaded the recording of these transactions https://drive.google.com/file/d/1TIAnjHlofj6kbDuVk_67WlBxgmaxLQdv and there are spans which is longer than 500 ms. And considering **/app/home** takes almost 1 sec page load it seems like transaction duration is also not correct.

**Comment by vigneshshanmugam** [comment] 2022-01-04 17:44
> We are using ELASTIC_APM_TRANSACTION_SAMPLE_RATE=1.0 which I believe preventing sampling. Are there any other variables we can use to totally disable sampling ?

I dont think so, we may need to check if the browsers does report those resource timing data. A simple check with resource timing API would help here - `performance.getEntriesByType("resource")` https://developer.mozilla.org/en-US/docs/Web/API/Performance/getEntriesByType

We can also discuss offline to find the issue. Do you want to schedule a call and include both of us?

**Comment by vigneshshanmugam** [comment] 2022-02-08 19:17
@suchcodemuchwow Do you need any more details here or we can close the issue if there is nothing needed from our side? Thanks!

**Closed** 2022-02-11 17:06 UTC
