### ISSUE TITLE
Send RUM events for all activity (including partial page loads that don't reach onLoad)

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/apm-agent-rum-js#970] opened 2021-02-24 17:40 UTC
As a consumer of RUM information
I want to have any load activity captured and beaconed back, even if it doesn't reach the full page load
So that I have a complete record of actual traffic on my site
And that impression numbers match up better with other analytics platforms 
And that slower devices or devices on slower connections aren't under represented in my data and biasing my analysis
And see if there is a gap between number of impressions and the number of full page loads in my data to understand if I have problems with code executing in the browser in production

**Comment by paulb-elastic** [comment] 2021-02-24 17:47
Considered during discussions within https://github.com/elastic/synthetics/issues/223

**Comment by jahtalab** [comment] 2021-04-22 12:07
Related issue: - [Consider using Beacon API for sending payload on `unload` event · Issue #195 · elastic/apm-agent-rum-js](https://github.com/elastic/apm-agent-rum-js/issues/195)

**Comment by paulb-elastic** [comment] 2022-02-23 11:52
https://github.com/elastic/apm-agent-rum-js/pull/1146 adds this for Chrome and Safari (WebKit)

**Comment by vigneshshanmugam** [comment] 2022-02-23 18:59
We still don't have a test for the partial loads and only have for hidden/backgrounded pages, exits that happens post onload. 

@devcorpio Can we add a small test for the same and close this issue, What are your thoughts?

**Comment by devcorpio** [comment] 2022-03-14 11:22
@vigneshshanmugam, the closest thing we have for testing partial loads are the following tests:

https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum-core/test/common/page-visibility.spec.js#L138

Those tests check what would it happen if a page is backgrounded somehow while a transaction is still opened (page load is an example of transaction).

Are those tests I'm linking what you have in mind? Or are you thinking of an explicit e2e test? 

If it's the latter we should find a way to simulate a "slow" page load somehow (e.g. load a page with heavy resources, throttle browser connection, etc), and then inspect the payload and identify the `page-load` transaction after backgrounding the page. I'm not sure if we can set those kind of requirements with karma and probably we should leverage the power of synthetics/playwright to do a test of that kind. (Please, correct me if I'm being too imaginative 😄 )

An additional note: I would dare to say that with the tests linked above might be enough since with the e2e test what we would be executing are the same APIs but before the **pageload**, like if we were testing if the **browser** acts properly. It's also true that it would be helpful to pinpoint possible browser regressions on that matter

**Closed** 2022-03-24 10:47 UTC
